export const fieldList = () => [
  "Preferred Language",
  "Advertisement No",
  "Speciality/Super Speciality",
  "Post Applied For",
  "Whether belongs to Persons with Disability (PWBD) category ?",
  "PWBD(%):",
  "PWBD Category",
  "PWBD sub Category",
  "Category",
  "Preferred Department List",
  "Father's Name",
  "Mother's Name",
  "Gender",
  "Nationality",
  "Are You Regular Govt. Servant?",
  "Date of Appointment",
  "Till Date",
  "Date of Birth",
  "Marital Status",
  "A Citizen of India by birth or by domicile?",
  "ID Proof:",
  "ID No:",
  "Alternate Number",
  "Permanent Address",
  "Postal Address",
  "Required Education Qualification Details",
  "Other Education Qualification Details",
  "Registration Details",
  "Work Experience",
  "1.1. Undergraduate Education",
  "1.2. NTSC Scholarship Winner in School",
  "1.3. Postgraduate education",
  "1.4. Senior Resident",
  "1.5. Work experience",
  "1.6. International Fellowship from Non-LMIC Country",
  "1.7. Served in Armed Forces",
  "1.8. BCLS (Basic Cardiac Life Support) course.",
  "1.9. NELS (National Emergency Life Support) / ACLS (Advanced Cardiac Life Support) course.",
  "2.1. Pubmed Indexed Publication",
  "2.2. Thesis Publication",
  "2.3. Google Scholar H-Index Number",
  "2.4. Book Chapter Published",
  "2.5. Funded project from ICMR/ DST/SERB/DBT/ CSIR/International",
  "2.6.Accepted Patent",
  "3.1. Oral Presentation/Lecture in National Conference/Workshop",
  "3.2. Poster Presentation in National Conferences",
  "3.3. Oral Presentation/Lecture in International Conferences organized by Scientific Association.",
  "3.4. Poster Presentation at an International Conference organized by a Scientific Association.",
  "3.5. Attended Basic Course Workshop in Medical Education Technologies (NMC).",
  "3.6. Attended Advanced Course in Medical Education (ACME) (NMC).",
  "3.7. NMC course in Biomedical Research.",
  "3.8. Attended Curriculum Implementation Support Program (CISP) (NMC).",
  "3.9. International (e.g. FAIMER) / Advanced Course in Research Methodology",
  "Publication and Research Work Details",
  "Your Best Paper",
  "Research Project as Chief Investigator or Co-Investigator",
  "Awards, Fellowships and Membership of Professional Bodies Details",
  "Membership of Editorial Boards of Indexed International Journal/Review Committees at National Bodies and Institution Details",
  "Service Details (Contribution made towards the development of new Unit/ Speciality/ Laboratory/ Facility/ Programs/ Therapeutic or Diagnostic Procedures developed or Patents taken(enclosed evidence))",
  "Contribution Details in Community and National Programmes",
  "Describe your most notable contribution to education, research and healthcare (1000 Characters)",
  "In your understanding, what are the top 5 current priorities of the Institute within its mandate? (3000 Characters)",
  "What will be your medium to long term research focus and strategy, if selected (1000 Characters)",
  "Profile Photo",
  "Signature",
  "Left Thumb Impression",
];
